--------------------------------------------------------
-- Archivo creado  - jueves-julio-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "DFRANKDB"."PLAYER" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"NICK" VARCHAR2(100 BYTE), 
	"NICK_NO_COLOR" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE" ;
REM INSERTING into DFRANKDB.PLAYER
SET DEFINE OFF;
Insert into DFRANKDB.PLAYER (EMAIL,NOMBRE,NICK,NICK_NO_COLOR,APELLIDOS,PASSWORD) values ('patocueck@gmail.com','Patricio','^4ZzZ^1|Hoopz','ZzZ|Hoopz','Zuniga','123');
--------------------------------------------------------
--  DDL for Index PLAYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DFRANKDB"."PLAYER_PK" ON "DFRANKDB"."PLAYER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE" ;
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "DFRANKDB"."PLAYER" ADD CONSTRAINT "PLAYER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE"  ENABLE;
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("NICK_NO_COLOR" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("NICK" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."PLAYER" MODIFY ("EMAIL" NOT NULL ENABLE);
