--------------------------------------------------------
-- Archivo creado  - jueves-julio-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIME
--------------------------------------------------------

  CREATE TABLE "DFRANKDB"."TIME" 
   (	"ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MAP" VARCHAR2(100 BYTE), 
	"TIME" TIMESTAMP (6), 
	"PHYSIC" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE" ;
REM INSERTING into DFRANKDB.TIME
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DFRANKDB"."TIME_PK" ON "DFRANKDB"."TIME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE" ;
--------------------------------------------------------
--  Constraints for Table TIME
--------------------------------------------------------

  ALTER TABLE "DFRANKDB"."TIME" ADD CONSTRAINT "TIME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFRANKDB_TABSPACE"  ENABLE;
  ALTER TABLE "DFRANKDB"."TIME" MODIFY ("PHYSIC" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."TIME" MODIFY ("MAP" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."TIME" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DFRANKDB"."TIME" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TIME_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DFRANKDB"."TIME_TRG" 
BEFORE INSERT ON TIME 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TIME_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DFRANKDB"."TIME_TRG" ENABLE;
